### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by tnrich** [electerious/basicContext#18]
Hey there,

It looks like you've built an awesome, easy to use component, but I'm hesitant to use it because it looks like development on it has stalled. There are still features I would like to use that don't appear to have been implemented yet, namely the sub-menu functionality. 

So, will development continue for this tool?

Thanks!

**Comment by tnrich** [comment]
Appears that it isn't... @electerious , you still alive?

**Comment by electerious** [comment]
It's still maintained, but there isn't much progress at the moment. It works and I'm not aware of any big problems.

I implemented a sub-menu functionality in the v4.0 branch (a complete rewrite), but failed to finish it. Getting sub-menus correct is really hard. Lots of details that make the implementation a pain (e.g. http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown). I still have the plan to do (another) rewrite by time.
