### ISSUE TITLE
Passing the target element down?

### ISSUE THREAD

**Issue by rangitha** [electerious/basicContext#21]
From a cursory look at the source code, it seems to me that the element on which the contextual actions are performed is not passed down to the functions that are invoked for menu items.

Is this already possible or would this be a good addition to the library if implemented?

**Comment by electerious** [comment]
Yes, the element gets not passed down. Here's how you could do it:

```
document.querySelector('.btn').addEventListener('click', function(e) {

	let items = [
		{ title: 'Add Sites', icon: 'ion-plus-round', fn: clicked.bind(null, e.target) },
		// or
		{ title: 'Add Sites', icon: 'ion-plus-round', fn: clicked.bind(e.target) }
	]

	basicContext.show(items, e)

})
```

I hope this is a solution to your problem! :)
