### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by devmondo** [electerious/basicContext#8]
lovely, short written, cool menu, i love it and i love that there is no jquery involved:)
some ideas if you dont mind

 - ability to select where the menu you will show relative to the element, maybe left to it, above it or on top of it, etc..
- the scroll demo is cool, but the scroll bars are so large and the menu it self is so narrow

all the best and thanks again for simple awesome work :)

**Comment by electerious** [comment]
Thanks for the suggestions! :)

- I will add some padding to the box if scroll bars are visible. I think that's a good idea.
- You can pass custom coordinates to basicContext, but that's currently not documented. The ability to select where the menu shows (e.g. above, left or right) isn't planned.

**Comment by electerious** [comment]
- [ ] Padding when scrollbars visible
- [ ] Demo for custom coordinates

**Comment by devmondo** [comment]
:+1:
